# Generated by Django 4.1.5 on 2023-02-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_remove_ride_driver_ride_passengers_ride_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
