# Generated by Django 4.1.5 on 2023-02-03 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0004_alter_vehicle_brand_alter_vehicle_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='number_of_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='special_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('COMPLETE', 'Complete')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupé'), ('CONV', 'Convertible'), ('SUV', 'SUV'), ('VAN', 'Van'), ('WAGON', 'Wagon'), ('SPORT', 'Sports car'), ('NONE', 'Unknown')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupé'), ('CONV', 'Convertible'), ('SUV', 'SUV'), ('VAN', 'Van'), ('WAGON', 'Wagon'), ('SPORT', 'Sports car'), ('NONE', 'Unknown')], default='NONE', max_length=5),
        ),
    ]
