# Generated by Django 4.1.5 on 2023-02-03 04:15

from django.db import migrations, models
import ride.models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_remove_ride_end_time_remove_ride_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, validators=[ride.models.validate_not_earlier_than_now]),
        ),
    ]
