# Generated by Django 4.1.5 on 2023-02-03 04:16

from django.db import migrations, models
import ride.models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_alter_ride_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateField(blank=True, null=True, validators=[ride.models.validate_not_earlier_than_now]),
        ),
    ]
