# Generated by Django 4.1.5 on 2023-02-03 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ride.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0007_alter_ride_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, validators=[ride.models.validate_not_earlier_than_now]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
