# Generated by Django 4.1.5 on 2023-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_ride_driver_alter_ride_arrival_time_alter_ride_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('NONE', 'Unknown'), ('SEDAN', 'Sedan'), ('COUPE', 'Coupé'), ('CONV', 'Convertible'), ('SUV', 'SUV'), ('VAN', 'Van'), ('WAGON', 'Wagon'), ('SPORT', 'Sports car'), ('OTHER', 'Other')], default='NONE', max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('NONE', 'Unknown'), ('SEDAN', 'Sedan'), ('COUPE', 'Coupé'), ('CONV', 'Convertible'), ('SUV', 'SUV'), ('VAN', 'Van'), ('WAGON', 'Wagon'), ('SPORT', 'Sports car'), ('OTHER', 'Other')], default='NONE', max_length=5),
        ),
    ]
