# Generated by Django 4.1.5 on 2023-02-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_alter_ride_vehicle_type_alter_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='special_vehicle_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Plate number'),
        ),
    ]
