# Generated by Django 4.1.5 on 2023-02-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ride.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0010_vehicle_special_vehicle_info_alter_vehicle_plate_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('earliest_time', models.DateTimeField(blank=True, null=True, validators=[ride.models.validate_not_earlier_than_now])),
                ('latest_time', models.DateTimeField(blank=True, null=True, validators=[ride.models.validate_not_earlier_than_now])),
                ('number_of_passengers', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_rides_detail', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ride.ride')),
            ],
        ),
    ]
