# Generated by Django 4.1.5 on 2023-02-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0011_shareride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='number_of_passengers_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
