# Generated by Django 4.1.5 on 2023-02-02 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Is a Driver'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='my_ride',
            field=models.ManyToManyField(to='ride.ride', verbose_name='My Rides'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='my_vehicle',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ride.vehicle', verbose_name='My Vehicle'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, verbose_name='Phone Number'),
        ),
    ]
