# Generated by Django 4.1.5 on 2023-02-02 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
        ('account', '0002_myuser_is_driver_myuser_my_ride_myuser_my_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='my_vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ride.vehicle', verbose_name='My Vehicle'),
        ),
    ]
