# Generated by Django 4.1.5 on 2023-02-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
        ('account', '0004_alter_myuser_my_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='my_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ride.vehicle', verbose_name='My Vehicle'),
        ),
    ]
