# Generated by Django 4.1.5 on 2023-02-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_myuser_my_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='my_vehicle',
        ),
    ]
