# Generated by Django 4.1.5 on 2023-02-02 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_remove_ride_driver_ride_passengers_ride_vehicle'),
        ('account', '0006_remove_myuser_my_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='my_ride',
        ),
        migrations.AddField(
            model_name='myuser',
            name='vehicle',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ride.vehicle', verbose_name='My Vehicle'),
        ),
    ]
