# Generated by Django 4.1.5 on 2023-02-02 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_remove_ride_driver_ride_passengers_ride_vehicle'),
        ('account', '0007_remove_myuser_my_ride_myuser_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='vehicle',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ride.vehicle', verbose_name='My Vehicle'),
        ),
    ]
