# Generated by Django 4.1.5 on 2023-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_alter_ride_vehicle_type_alter_vehicle_type'),
        ('account', '0011_myuser_sharer_rides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sharer_rides',
            field=models.ManyToManyField(blank=True, null=True, related_name='sharers', to='ride.ride'),
        ),
    ]
