# Generated by Django 4.1.6 on 2023-02-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0012_ride_number_of_passengers_sum'),
        ('account', '0012_alter_myuser_sharer_rides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='sharer_rides',
            field=models.ManyToManyField(blank=True, related_name='sharers', to='ride.ride'),
        ),
    ]
